### ISSUE TITLE
Cloc ignoring .gitignore

### ISSUE THREAD

**Issue by fmpanelli** [EnricoPicci/git-metrics#1]
Thank you Enrico for the effort you are putting into this. I think it's a powerful idea.

I am sharing this (probably low-hanging) opportunity for improving the tool.
I hope it is useful.

## Steps to reproduce

- have a local repo folder with `.gitignore`-d files (e.g. a Python `env` folder with `*.py` files) with the same extension you want to analyze
- run `npx git-metrics` on that repo including that file extension
- verify the produced `cloc` file contains also the files that are ignored by `git` according to `.gitignore`

## Expected behavior

Files and folders specified in `.gitignore` should be ignored by `git-metrics`

## Suggested approach

When invoking `cloc` use the `--vcs git` option instead of `--exclude-dir=node_modules`.
See [AlDanial/cloc](https://github.com/AlDanial/cloc) on github.

**Comment by EnricoPicci** [comment]
Closed as suggested with commit "1.1.8"

**Comment by fmpanelli** [comment]
Thank you!
